### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by zoffyultraman** [YukiCoco/CheapSteam#5]
Unhandled exception. System.NullRefernenceException:Object refernce not set to an instance of an objiect
  at ChpStmScraper.Program.<>c_DisplayClass13_1.<start>b_2(Object state)
  at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
  at System.Threading.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

系统环境为：windows10 20H2 OS内部版本19042.746

**Comment by zoffyultraman** [comment]
发现已解决的里面有类似情况。已尝试，谢谢。
